<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dante.Application/Dante.Application.csproj" />
    <ProjectReference Include="../Dante.Infrastructure/Dante.Infrastructure.csproj" />
  </ItemGroup>
</Project>
