// <auto-generated />
using System;
using Dante.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dante.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(DanteDbContext))]
    [Migration("20261005211631_IndicesDerivadosDeBusca")]
    partial class IndicesDerivadosDeBusca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("brain_data")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dante.Domain.CapturaDeConhecimento.CandidatoDeConhecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("conteudo");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<Guid?>("IdConhecimento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_conhecimento");

                    b.Property<Guid>("IdEspacoDeConhecimento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_espaco_de_conhecimento");

                    b.Property<Guid?>("IdIncidente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_incidente");

                    b.Property<Guid?>("IdProjeto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_projeto");

                    b.Property<Guid?>("IdSolucao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_solucao");

                    b.Property<string>("Impressao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("impressao");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("justificativa");

                    b.Property<int>("Modo")
                        .HasColumnType("integer")
                        .HasColumnName("modo");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer")
                        .HasColumnName("natureza");

                    b.Property<int>("Sensibilidade")
                        .HasColumnType("integer")
                        .HasColumnName("sensibilidade");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("historico")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("historico");

                    b.HasKey("Id");

                    b.HasIndex("IdConhecimento", "IdEspacoDeConhecimento");

                    b.HasIndex("IdIncidente", "IdEspacoDeConhecimento");

                    b.HasIndex("IdProjeto", "IdEspacoDeConhecimento");

                    b.HasIndex("IdSolucao", "IdEspacoDeConhecimento");

                    b.HasIndex("IdEspacoDeConhecimento", "IdProjeto", "Estado");

                    b.HasIndex("IdEspacoDeConhecimento", "IdProjeto", "Impressao")
                        .IsUnique()
                        .HasDatabaseName("IX_candidatos_de_conhecimento_id_espaco_de_conhecimento_id_pr~1");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("IdEspacoDeConhecimento", "IdProjeto", "Impressao"), false);

                    b.ToTable("candidatos_de_conhecimento", "brain_data");
                });

            modelBuilder.Entity("Dante.Domain.Conhecimentos.Conhecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<double?>("Confianca")
                        .HasColumnType("double precision")
                        .HasColumnName("confianca");

                    b.Property<string>("Conteudo")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DadosEstruturados")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_estruturados");

                    b.Property<Guid>("IdAutor")
                        .HasColumnType("uuid")
                        .HasColumnName("id_autor");

                    b.Property<Guid?>("IdConhecimentoSubstituto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_conhecimento_substituto");

                    b.Property<Guid>("IdEspacoDeConhecimento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_espaco_de_conhecimento");

                    b.Property<Guid?>("IdProjeto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_projeto");

                    b.Property<int>("Sensibilidade")
                        .HasColumnType("integer")
                        .HasColumnName("sensibilidade");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("ValidoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valido_ate");

                    b.Property<DateTimeOffset?>("ValidoDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valido_desde");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("historico")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("historico");

                    b.HasKey("Id");

                    b.HasIndex("IdConhecimentoSubstituto", "IdEspacoDeConhecimento");

                    b.HasIndex("IdProjeto", "IdEspacoDeConhecimento");

                    b.HasIndex("IdEspacoDeConhecimento", "IdProjeto", "Status");

                    b.ToTable("conhecimentos", "brain_data");
                });

            modelBuilder.Entity("Dante.Domain.EspacosDeConhecimento.EspacoDeConhecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "Estado");

                    b.ToTable("espacos_de_conhecimento", "brain_data");
                });

            modelBuilder.Entity("Dante.Domain.Projetos.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AliasDoRepositorio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias_do_repositorio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<Guid>("IdEspacoDeConhecimento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_espaco_de_conhecimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdEspacoDeConhecimento", "Estado");

                    b.ToTable("projetos", "brain_data");
                });

            modelBuilder.Entity("Dante.Domain.RelacoesDeConhecimento.RelacaoDeConhecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<Guid>("IdDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_destino");

                    b.Property<Guid>("IdEspacoDeConhecimento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_espaco_de_conhecimento");

                    b.Property<Guid>("IdOrigem")
                        .HasColumnType("uuid")
                        .HasColumnName("id_origem");

                    b.Property<Guid?>("IdProjeto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_projeto");

                    b.Property<string>("Proveniencia")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("proveniencia");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdDestino", "IdEspacoDeConhecimento");

                    b.HasIndex("IdEspacoDeConhecimento", "IdDestino");

                    b.HasIndex("IdOrigem", "IdEspacoDeConhecimento");

                    b.HasIndex("IdEspacoDeConhecimento", "IdOrigem", "IdDestino", "Tipo")
                        .IsUnique();

                    b.ToTable("relacoes_de_conhecimento", "brain_data");
                });

            modelBuilder.Entity("Dante.Domain.CapturaDeConhecimento.CandidatoDeConhecimento", b =>
                {
                    b.HasOne("Dante.Domain.EspacosDeConhecimento.EspacoDeConhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dante.Domain.Conhecimentos.Conhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdConhecimento", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dante.Domain.Conhecimentos.Conhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdIncidente", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dante.Domain.Projetos.Projeto", null)
                        .WithMany()
                        .HasForeignKey("IdProjeto", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dante.Domain.Conhecimentos.Conhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdSolucao", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dante.Domain.Conhecimentos.Conhecimento", b =>
                {
                    b.HasOne("Dante.Domain.EspacosDeConhecimento.EspacoDeConhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dante.Domain.Conhecimentos.Conhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdConhecimentoSubstituto", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dante.Domain.Projetos.Projeto", null)
                        .WithMany()
                        .HasForeignKey("IdProjeto", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dante.Domain.Projetos.Projeto", b =>
                {
                    b.HasOne("Dante.Domain.EspacosDeConhecimento.EspacoDeConhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dante.Domain.RelacoesDeConhecimento.RelacaoDeConhecimento", b =>
                {
                    b.HasOne("Dante.Domain.Conhecimentos.Conhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdDestino", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dante.Domain.Conhecimentos.Conhecimento", null)
                        .WithMany()
                        .HasForeignKey("IdOrigem", "IdEspacoDeConhecimento")
                        .HasPrincipalKey("Id", "IdEspacoDeConhecimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
